In [1]:
import numpy as np
from pickle import load

In [ ]:
from pickle import load
ohe =load(open('models/one_hot_encoding.pkl', 'rb'))
scaler=load(open('models/standard_scaler.pkl','rb'))
label_enc=load(open('models/grade.pkl','rb'))


knn_classifier = load(open('models/knn_model.pkl', 'rb'))
lr_classifier = load(open('models/lr_model.pkl', 'rb'))
dt_classifier = load(open('models/dt_model.pkl', 'rb'))
sv_classifier = load(open('models/sv_model.pkl', 'rb'))
rf_classifier = load(open('models/rf_model.pkl', 'rb'))

In [ ]:
# Read the Query Data

print("Enter Banking Details")
age = float(input('Enter the Person Age: '))
income = float(input('Enter the Person Income: '))
emp_length = float(input('Enter the Person Employee Length: '))
loan_amt = float(input('Enter the Loan Amount: '))
loan_int_rate= float(input('Enter the Loan Interest Rate: '))
loan_percent_income= float(input('Enter the Loan Percent Income: '))
cb_person_cred_hist_length= float(input('Enter Person Credit History Length: '))
person_home_ownership=input('Enter Person Home Ownership: ')
loan_intent=input('Enter Loan Intent: ')
loan_grade=input('Enter Loan Grade: ')
cb_person_default_on_file=input('Enter Historic Default: ')

Enter Banking Details


In [ ]:
print(age,income,emp_length,loan_amt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,person_home_ownership,loan_intent,loan_grade,cb_person_default_on_file)

21.0 9600.0 5.0 1000.0 11.14 0.1 2.0 OWN EDUCATION B N


In [ ]:
query_point = np.array([age,income,emp_length,loan_amt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length]).reshape(1, -1)

In [ ]:
# query_point=query_point.astype(int)

In [ ]:
query_point_transformed = scaler.transform(query_point)

In [ ]:
query_point_ohe=np.array([person_home_ownership,loan_intent,
       cb_person_default_on_file]).reshape(1,-1)

In [ ]:
query_point_ohe

array([['OWN', 'EDUCATION', 'N']], dtype='<U9')

In [ ]:
query_point_transformed_ohe = ohe.transform(query_point_ohe)

In [ ]:
query_point_transformed_ohe=query_point_transformed_ohe.astype(int)

In [ ]:
for i in query_point_transformed_ohe:
    print(i)

[0 1 0 1 0 0 0 0 0]


In [ ]:
query_point_transformed_ohe

array([[0, 1, 0, 1, 0, 0, 0, 0, 0]])

In [ ]:
# label encoder
print(grade_encoder)

{'G': 7, 'F': 6, 'E': 5, 'D': 4, 'C': 3, 'B': 2, 'A': 1}


In [ ]:
loan_grade_transformed=[]
for i in grade_encoder:
    if i in loan_grade:
        print(loan_grade,grade_encoder[i])
        loan_grade_transformed.append(grade_encoder[i])


B 2


In [ ]:
query_point_lb = np.array([loan_grade_transformed[0]]).reshape(1,-1)
query_point_lb

array([[2]])

In [ ]:
new_query_point=np.append(query_point,query_point_transformed_ohe).reshape(1,-1)

In [ ]:
new_query_point1=np.append(new_query_point,query_point_lb).reshape(1,-1)

In [ ]:
print(query_point.shape,type(query_point))
print(query_point_ohe.shape,type(query_point_ohe))
print(query_point_lb.shape,type(query_point_lb))


(1, 7) <class 'numpy.ndarray'>
(1, 3) <class 'numpy.ndarray'>
(1, 1) <class 'numpy.ndarray'>


## Prediction

In [ ]:
pre=rf_classifier.predict(new_query_point1)
if pre==0:
    print("Non Default")
else:
    print("default")

Non Default
